services:
    app:
        image: azzazkhan/devcontainer-laravel:php-8.3
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www'
        networks:
            - sail
            - traefik
        labels:
            - traefik.enable=true
            - traefik.http.routers.laravel-vite.rule=Host(`vite.laravel.localhost`)
            - traefik.http.routers.laravel-vite.entrypoints=web
            - traefik.http.routers.laravel-vite.service=laravel-vite-service
            - traefik.http.services.laravel-vite-service.loadbalancer.server.port=5173

    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./docker/sail/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/sail/default.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - sail
            - traefik
        labels:
            - traefik.enable=true
            - traefik.http.routers.laravel.rule=Host(`${APP_DOMAIN:-laravel.localhost}`) || Host(`${API_DOMAIN:-api.laravel.localhost}`)
            - traefik.http.routers.laravel.entrypoints=web
            - traefik.http.routers.laravel.service=laravel-service
            - traefik.http.services.laravel-service.loadbalancer.server.port=80

networks:
    sail:
        driver: bridge
    traefik:
        external: true

volumes:
    sail-transformations:
        driver: local
